"""Compute article-level oracles and write ``article_oracle.json`` for all 24
article-variants (8 base articles × 3 variants = 24 total).

Reads
-----
``rl_training_data/bases/<article>/section_oracle.json``  (version 2)
    Per-section, per-arm rewards computed from episode run scoring.
    Generated by ``generate_episode_oracles.py``.

``rl_training_data/bases/<article>/guideline_features.json``
    Per-section ``target_words`` (weighting) and structural constraints
    (``mandatory_bullets``, ``must_cover_depth``).

``rl_training_data/episodes/<article>__preset<N>/article.md``
    Generated article text for each arm.  Used by signals S3 / S4 / S5.
    ARM → episode mapping:  skip=0  light=1  standard=3  deep=5

Decision scheme
---------------
1.  Compute **R_w** — target-words-weighted mean of per-arm rewards from
    ``section_oracle.json``.  This is the primary oracle signal.

2.  **Unique winner**: all arms are further than ``EPS_BAND = 0.02`` from the
    R_w leader → oracle = R_w leader.  No secondary signals needed.

3.  **Near-tie band** (≥2 arms within EPS_BAND of the leader):
    Apply signals in priority order, each with its own min-delta guard:
      S4  structural compliance  (mandatory_bullets + depth markers vs guideline)
      S3  article bloat          (word count / total target_words)
      S5  generation stability   (CV across 3 runs)
    A signal is applied as the decisive tiebreaker only when its spread across
    band arms ≥ its threshold.  ``needs_review=True`` when no signal clears
    its threshold; the cheapest arm in the band is used as a fallback.

4.  **Manual overrides** (analysis confirmed 2026-06-05):
    Four near-tie cases where the embedding-based S1 knee signal (not
    implemented here) was the decisive signal, and three where manual review
    overrode the automated result.  All verdicts are hard-coded and take
    absolute precedence over steps 1-3.

Note on S1 / S2: the marginal-novelty knee (S1) and intra-article redundancy
(S2) signals both require an embedding model and are not computed here.
For the current 24-variant training set every near-tie case where S1/S2 were
decisive is covered by the hard-coded manual overrides below.  If new
article-variants are added, re-run ``prototype_oracle_signals.py --all``
to get the full signal breakdown before updating this file.

Output schema  (article_oracle.json, version 2)
-----------------------------------------------
version               int   2
article               str   "10_memory_knowledge_access__var_standard"
variant               str   "var_minimal" | "var_standard" | "var_demanding"
computed_at           str   ISO-8601 UTC
oracle_arm            str   "skip" | "light" | "standard" | "deep"
oracle_arm_idx        int   0-3  (skip=0, light=1, standard=2, deep=3)
runner_up_arm         str
runner_up_arm_idx     int
margin                float oracle_r_w − runner_up_r_w
reward_spread         float max_r_w − min_r_w
r_w_rewards           dict  {arm: float}  (target-words-weighted)
r_w_rewards_list      list  [skip, light, standard, deep]  (indexed 0-3)
decision_path         list  human-readable trace of the decision
manual_override       bool
needs_review          bool
n_sections            int
n_sections_with_target int
total_target_words    int
sections              list  (see _build_section_records for fields)

Usage (from research_agent_local/training/)
    python compute_article_oracle.py               # all 24 variants
    python compute_article_oracle.py --article 10_memory_knowledge_access__var_standard
    python compute_article_oracle.py --dry-run

"""

from __future__ import annotations

import argparse
import datetime
import json
import re
import statistics
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_THIS_DIR = Path(__file__).resolve().parent
_AGENT_DIR = _THIS_DIR.parent               # research_agent_local/
_REPO_ROOT = _AGENT_DIR.parent              # RL_researcher_writer_ymaxing/
_BASES_DIR = _REPO_ROOT / "rl_training_data" / "bases"
_EPISODES_DIR = _REPO_ROOT / "rl_training_data" / "episodes"

# ---------------------------------------------------------------------------
# Preset / arm constants  (mirrors _rl_preset.py)
# ---------------------------------------------------------------------------
#: Ordered arm names (action space for the RL model).
ARMS: list[str] = ["skip", "light", "standard", "deep"]

#: Arm name → 0-based ordinal index.
ARM_IDX: dict[str, int] = {a: i for i, a in enumerate(ARMS)}

#: Arm name → episode preset ID used to generate its articles.
ARM_EPISODE: dict[str, int] = {"skip": 0, "light": 1, "standard": 3, "deep": 5}

#: Total number of arms.
NUM_ARMS: int = 4

# ---------------------------------------------------------------------------
# 24 training article-variants  (8 bases × 3 variants = 24)
# ---------------------------------------------------------------------------
_BASE_ARTICLES: list[str] = [
    "02_workflows_vs_agents",
    "03_context_engineering",
    "05_workflow_patterns",
    "06_tools",
    "08_react_practice",
    "09_RAG",
    "10_memory_knowledge_access",
    "11_multimodal",
]
_VARIANTS: list[str] = ["var_minimal", "var_standard", "var_demanding"]

ALL_ARTICLES: list[str] = [
    f"{base}__{var}"
    for base in _BASE_ARTICLES
    for var in _VARIANTS
]

# ---------------------------------------------------------------------------
# Decision constants  (must match prototype_oracle_signals.py)
# ---------------------------------------------------------------------------
EPS_BAND: float = 0.02      # near-tie tolerance: arms within this margin form the band
MIN_DELTA_S4: float = 0.05  # min structure signal spread to use S4 as tiebreaker
MIN_DELTA_S3: float = 0.10  # min bloat signal spread to use S3 as tiebreaker
MIN_DELTA_S5: float = 0.05  # min stability signal spread to use S5 as tiebreaker

# ---------------------------------------------------------------------------
# Manual overrides (all confirmed by 2026-06-05 session analysis)
#
# Key: article variant name  →  Value: confirmed oracle arm
#
# These take absolute precedence over every automated signal.
# Seven cases total:
#   · Two "manual review" cases where the automated signals were ambiguous
#     (needs_review=True) or the R_w winner was overridden after inspection.
#   · Two near-tie cases where the embedding-based S1 marginal-novelty knee
#     was the decisive signal.  Without the embedder, the production tiebreaker
#     (cheapest arm in band) would give a wrong answer, so the S1-confirmed
#     verdict is hard-coded here.
# ---------------------------------------------------------------------------
_MANUAL_OVERRIDES: dict[str, str] = {
    # --- manual review (needs_review=True or human inspection) ---
    "06_tools__var_minimal":               "skip",
    "11_multimodal__var_demanding":        "standard",

    # --- near-tie where S1 knee was decisive (no S4/S3/S5 actionable) ---
    # NOTE: 03_context_engineering__var_minimal removed — now covered by the
    #       external_evidence_policy=forbidden → skip hard constraint.
    "09_RAG__var_demanding":               "deep",
}

# ---------------------------------------------------------------------------
# Text helpers  (must match prototype_oracle_signals.py)
# ---------------------------------------------------------------------------
_BULLET_RE = re.compile(r"^\s*([-*+]|\d+[.)])\s+\S", re.MULTILINE)
_HEADING_RE = re.compile(r"^(#{1,6})\s+\S", re.MULTILINE)
_SUBHEAD_RE = re.compile(r"^#{3,6}\s+\S", re.MULTILINE)
_CODEFENCE_RE = re.compile(r"```")


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="ignore")
    except FileNotFoundError:
        return ""


def _word_count(text: str) -> int:
    return len(text.split())


# ---------------------------------------------------------------------------
# File loaders
# ---------------------------------------------------------------------------

def _load_section_oracle(article: str) -> dict:
    """Load and validate section_oracle.json v2 for *article*."""
    path = _BASES_DIR / article / "section_oracle.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    v = data.get("version", 1)
    if v < 2:
        raise ValueError(
            f"section_oracle.json for '{article}' is version {v}; "
            "version 2 required. Re-run generate_episode_oracles.py."
        )
    if not data.get("sections"):
        raise ValueError(f"section_oracle.json for '{article}' has no sections.")
    return data


def _load_guideline_features(article: str) -> dict:
    """Load guideline_features.json for *article*."""
    path = _BASES_DIR / article / "guideline_features.json"
    return json.loads(path.read_text(encoding="utf-8"))


def _read_article(article: str, arm: str) -> str:
    """Read the final article.md for *arm* (canonical run2, with fallbacks)."""
    ep_dir = _EPISODES_DIR / f"{article}__preset{ARM_EPISODE[arm]}"
    for name in ("article.md", "article_002.md", "article_001.md", "article_000.md"):
        p = ep_dir / name
        if p.exists():
            return _read_text(p)
    return ""


def _read_article_runs(article: str, arm: str) -> list[str]:
    """Read all 3 generation runs for *arm* (for stability signal S5)."""
    ep_dir = _EPISODES_DIR / f"{article}__preset{ARM_EPISODE[arm]}"
    return [
        _read_text(ep_dir / name)
        for name in ("article_000.md", "article_001.md", "article_002.md")
        if (ep_dir / name).exists()
    ]


# ---------------------------------------------------------------------------
# R_w  (target-words-weighted mean of per-arm section rewards)
# ---------------------------------------------------------------------------

def _compute_r_w(
    oracle_sections: dict[str, dict],
    features_sections: dict[str, dict],
) -> tuple[dict[str, float], int, int, int]:
    """Return (r_w_per_arm, total_target_words, n_sections, n_with_target).

    oracle_sections  : section_oracle.json["sections"]  {sec_id: {oracle, rewards}}
    features_sections: guideline_features.json["sections"]  {sec_id: {target_words, …}}
    """
    arm_acc: dict[str, float] = {a: 0.0 for a in ARMS}
    total_w = 0
    n_with_target = 0

    for sec_id, info in oracle_sections.items():
        rewards = info["rewards"]                          # {skip, light, standard, deep}
        feat = features_sections.get(sec_id, {})
        tw_val = feat.get("target_words")
        tw = int(tw_val) if tw_val is not None else 100   # fallback weight
        if tw_val is not None:
            n_with_target += 1
        total_w += tw
        for arm in ARMS:
            arm_acc[arm] += tw * float(rewards.get(arm, 0.0))

    if total_w == 0:
        return {a: 0.0 for a in ARMS}, 0, len(oracle_sections), n_with_target

    r_w = {a: arm_acc[a] / total_w for a in ARMS}
    return r_w, total_w, len(oracle_sections), n_with_target


# ---------------------------------------------------------------------------
# Signal S3: article length bloat  (article words / total target_words)
# ---------------------------------------------------------------------------

def _s3_bloat(article: str, total_target_words: int) -> dict[str, float]:
    """Lower is better (closer to target → less bloat)."""
    denom = max(total_target_words, 1)
    return {
        arm: round(_word_count(_read_article(article, arm)) / denom, 4)
        for arm in ARMS
    }


# ---------------------------------------------------------------------------
# Signal S4: structural compliance  (bullets + depth markers vs guideline)
# ---------------------------------------------------------------------------

def _s4_structure(
    article: str,
    features_sections: dict[str, dict],
) -> dict[str, float]:
    """Higher is better (closer to expected structural content).

    score = 0.6 × min(found_bullets / exp_bullets, 1)
          + 0.4 × min(depth_markers / exp_depth, 1)
    Both exp_bullets and exp_depth are clamped to ≥1 to avoid division by zero.
    depth_markers = subheadings (###-level) + code fences / 2.
    """
    exp_b = max(
        sum(int(f.get("mandatory_bullets", 0)) for f in features_sections.values()), 1
    )
    exp_d = max(
        sum(int(f.get("must_cover_depth", 0)) for f in features_sections.values()), 1
    )
    result: dict[str, float] = {}
    for arm in ARMS:
        text = _read_article(article, arm)
        found_b = len(_BULLET_RE.findall(text))
        depth_m = (
            len(_SUBHEAD_RE.findall(text))
            + (len(_CODEFENCE_RE.findall(text)) // 2)
        )
        b_score = min(1.0, found_b / exp_b)
        d_score = min(1.0, depth_m / exp_d)
        result[arm] = round(0.6 * b_score + 0.4 * d_score, 4)
    return result


# ---------------------------------------------------------------------------
# Signal S5: generation stability  (1 − mean CV across 3 runs)
# ---------------------------------------------------------------------------

def _cv(values: list[float]) -> float:
    mu = statistics.mean(values)
    return statistics.stdev(values) / mu if mu > 0 and len(values) > 1 else 0.0


def _s5_stability(article: str) -> dict[str, float]:
    """Higher is better (more consistent output across runs)."""
    result: dict[str, float] = {}
    for arm in ARMS:
        runs = _read_article_runs(article, arm)
        if len(runs) < 2:
            result[arm] = 1.0
            continue
        wc = [_word_count(r) for r in runs]
        hc = [len(_HEADING_RE.findall(r)) for r in runs]
        bc = [len(_BULLET_RE.findall(r)) for r in runs]
        cvs = [_cv(wc), _cv(hc), _cv(bc)]
        result[arm] = round(max(0.0, 1.0 - statistics.mean(cvs)), 4)
    return result


# ---------------------------------------------------------------------------
# Min-delta guard
# ---------------------------------------------------------------------------

def _has_actionable_delta(
    band: list[str], signal: dict[str, float], min_delta: float
) -> bool:
    """True iff signal spread across band arms ≥ min_delta (not within noise)."""
    vals = [signal[a] for a in band if signal[a] == signal[a]]  # skip NaN
    return len(vals) >= 2 and (max(vals) - min(vals)) >= min_delta


# ---------------------------------------------------------------------------
# Oracle decision
# ---------------------------------------------------------------------------

def _decide(
    article: str,
    r_w: dict[str, float],
    features_sections: dict[str, dict],
    total_target_words: int,
    external_evidence_policy: str = "allowed",
) -> tuple[str, bool, bool, list[str]]:
    """Return (oracle_arm, manual_override, needs_review, decision_path).

    decision_path is a human-readable list of strings tracing the decision.
    """
    # -1. Hard constraint: forbidden policy → skip, regardless of R_w.
    #     External evidence cannot be used in the final article, so the only
    #     valid production choice is the no-exploration arm.
    if external_evidence_policy == "forbidden":
        return "skip", False, False, ["policy=forbidden → skip (hard constraint)"]

    # 0.  Manual override: absolute precedence over all signals.
    if article in _MANUAL_OVERRIDES:
        arm = _MANUAL_OVERRIDES[article]
        return arm, True, False, [f"manual override → {arm}"]

    # 1.  Sort all arms by R_w descending.
    ranked = sorted(ARMS, key=lambda a: r_w[a], reverse=True)
    best_arm = ranked[0]
    best_r = r_w[best_arm]

    # 2.  Build near-tie band: all arms within EPS_BAND of the leader.
    band = [a for a in ARMS if best_r - r_w[a] <= EPS_BAND]

    if len(band) == 1:
        margin = best_r - r_w[ranked[1]]
        return best_arm, False, False, [
            f"unique reward winner (margin={margin:+.4f} > EPS_BAND={EPS_BAND})"
        ]

    # 3.  Near-tie: compute text-based signals and apply them in priority order.
    path: list[str] = [
        f"near-tie band={band} "
        f"R_w=[{', '.join(f'{a}:{r_w[a]:.4f}' for a in band)}]"
    ]

    s4 = _s4_structure(article, features_sections)
    s3 = _s3_bloat(article, total_target_words)
    s5 = _s5_stability(article)

    s4_active = _has_actionable_delta(band, s4, MIN_DELTA_S4)
    s3_active = _has_actionable_delta(band, s3, MIN_DELTA_S3)
    s5_active = _has_actionable_delta(band, s5, MIN_DELTA_S5)
    any_active = s4_active or s3_active or s5_active

    def _safe(x: float, default: float = 0.0) -> float:
        return default if x != x else x  # NaN → default

    # Priority key: (S4 higher-is-better, S3 lower-is-better, S5 higher-is-better,
    #                cheapest arm as final tie-breaker)
    def _key(arm: str) -> tuple:
        return (
            -(_safe(s4[arm]) if s4_active else 0.0),
            (_safe(s3[arm], 9.9) if s3_active else 0.0),
            -(_safe(s5[arm]) if s5_active else 0.0),
            ARMS.index(arm),   # cheaper arm (lower index) wins on full tie
        )

    winner = min(band, key=_key)

    active_labels = [
        lbl for lbl, flag in [
            (f"S4(Δ≥{MIN_DELTA_S4})", s4_active),
            (f"S3(Δ≥{MIN_DELTA_S3})", s3_active),
            (f"S5(Δ≥{MIN_DELTA_S5})", s5_active),
        ] if flag
    ]
    if active_labels:
        path.append(
            f"active signals: [{', '.join(active_labels)}]  winner={winner}  "
            f"S4={{{', '.join(f'{a}:{s4[a]:.3f}' for a in band)}}}  "
            f"S5={{{', '.join(f'{a}:{s5[a]:.3f}' for a in band)}}}"
        )
    else:
        path.append(
            f"no signal cleared its threshold → needs_review=True  "
            f"fallback=cheapest arm in band ({winner})"
        )

    return winner, False, not any_active, path


# ---------------------------------------------------------------------------
# Build per-section output records
# ---------------------------------------------------------------------------

def _sec_id_to_title(sec_id: str) -> str:
    """Convert 'S3::section-3-choosing-your-path' → 'choosing your path'."""
    m = re.match(r"S\d+::section-\d+-(.+)$", sec_id)
    return m.group(1).replace("-", " ") if m else sec_id


def _build_section_records(
    oracle_sections: dict[str, dict],
    features_sections: dict[str, dict],
    total_target_words: int,
) -> list[dict]:
    records = []
    for i, (sec_id, info) in enumerate(oracle_sections.items()):
        rewards = info["rewards"]
        feat = features_sections.get(sec_id, {})
        tw_val = feat.get("target_words")
        tw = int(tw_val) if tw_val is not None else 100
        weight_frac = round(tw / total_target_words, 5) if total_target_words > 0 else 0.0

        sec_ranked = sorted(ARMS, key=lambda a: float(rewards.get(a, 0.0)), reverse=True)
        records.append({
            "index": i + 1,
            "sec_id": sec_id,
            "title": _sec_id_to_title(sec_id),
            "target_words": tw_val,
            "weight_words": tw,
            "weight_frac": weight_frac,
            # rewards keyed by arm name
            "rewards": {a: round(float(rewards.get(a, 0.0)), 6) for a in ARMS},
            # rewards as a list indexed 0=skip, 1=light, 2=standard, 3=deep
            # used by analyze_eval_results.py for section reward-gap analysis
            "rewards_by_preset": [
                round(float(rewards.get(a, 0.0)), 6) for a in ARMS
            ],
            "section_oracle": info.get("oracle", sec_ranked[0]),
            "section_oracle_idx": ARM_IDX.get(info.get("oracle", sec_ranked[0]), 0),
        })
    return records


# ---------------------------------------------------------------------------
# Main per-variant computation
# ---------------------------------------------------------------------------

def _variant_of(article: str) -> str:
    if "__var_minimal" in article:
        return "var_minimal"
    if "__var_demanding" in article:
        return "var_demanding"
    return "var_standard"


def compute_article_oracle(article: str) -> dict:
    """Compute the full article-level oracle record for one variant.

    Returns a dict ready for JSON serialisation matching the schema in
    this module's docstring.
    """
    # --- load inputs ---
    oracle_data = _load_section_oracle(article)
    oracle_sections: dict[str, dict] = oracle_data["sections"]

    feat_data = _load_guideline_features(article)
    features_sections: dict[str, dict] = feat_data.get("sections", {})

    # --- R_w ---
    r_w, total_tw, n_sections, n_with_target = _compute_r_w(
        oracle_sections, features_sections
    )

    # --- decision ---
    oracle_arm, manual_override, needs_review, decision_path = _decide(
        article, r_w, features_sections, total_tw,
        external_evidence_policy=feat_data.get("external_evidence_policy", "allowed"),
    )
    oracle_arm_idx = ARM_IDX[oracle_arm]

    runner_up_arm = max(
        (a for a in ARMS if a != oracle_arm), key=lambda a: r_w[a]
    )
    runner_up_arm_idx = ARM_IDX[runner_up_arm]
    margin = r_w[oracle_arm] - r_w[runner_up_arm]
    reward_spread = max(r_w.values()) - min(r_w.values())

    # --- section records ---
    section_records = _build_section_records(
        oracle_sections, features_sections, total_tw
    )

    return {
        "version": 2,
        "article": article,
        "variant": _variant_of(article),
        "computed_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "oracle_arm": oracle_arm,
        "oracle_arm_idx": oracle_arm_idx,
        "runner_up_arm": runner_up_arm,
        "runner_up_arm_idx": runner_up_arm_idx,
        "margin": round(margin, 6),
        "reward_spread": round(reward_spread, 6),
        "r_w_rewards": {a: round(r_w[a], 6) for a in ARMS},
        "r_w_rewards_list": [round(r_w[a], 6) for a in ARMS],
        "decision_path": decision_path,
        "manual_override": manual_override,
        "needs_review": needs_review,
        "n_sections": n_sections,
        "n_sections_with_target": n_with_target,
        "total_target_words": total_tw,
        "sections": section_records,
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Compute article-level oracles from section_oracle.json v2 "
            "and write article_oracle.json for all 24 training variants."
        )
    )
    parser.add_argument(
        "--article",
        type=str,
        default=None,
        metavar="NAME",
        help="Process only this article-variant (default: all 24).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print results to stdout; do not write any files.",
    )
    args = parser.parse_args()

    if args.article:
        if args.article not in ALL_ARTICLES:
            sys.exit(
                f"ERROR: unknown article '{args.article}'.\nValid choices:\n"
                + "\n".join(f"  {a}" for a in ALL_ARTICLES)
            )
        targets = [args.article]
    else:
        targets = ALL_ARTICLES

    mode = "DRY-RUN" if args.dry_run else "WRITE"
    print(
        f"compute_article_oracle.py  [{mode}]  "
        f"4-arm scheme (skip/light/standard/deep)\n"
        f"  Targets: {len(targets)} article-variant(s)\n"
    )

    results: list[dict] = []
    errors: list[tuple[str, str]] = []

    for article in targets:
        try:
            print(f"  {article} ...", end=" ", flush=True)
            data = compute_article_oracle(article)
            results.append(data)

            flag = " ★OVERRIDE" if data["manual_override"] else ""
            flag += " ⚠REVIEW" if data["needs_review"] else ""
            r_w_str = "  ".join(
                f"{a}={data['r_w_rewards'][a]:.3f}" for a in ARMS
            )
            print(
                f"oracle={data['oracle_arm']:<8}  "
                f"margin={data['margin']:+.4f}  "
                f"R_w=[{r_w_str}]{flag}"
            )

            if not args.dry_run:
                out_path = _BASES_DIR / article / "article_oracle.json"
                out_path.write_text(
                    json.dumps(data, indent=2), encoding="utf-8"
                )

        except Exception as exc:
            print(f"  ERROR: {exc}")
            errors.append((article, str(exc)))

    # --- summary table ---
    if results:
        col_w = max(len(d["article"]) for d in results) + 2
        print()
        print(
            f"  {'Article':<{col_w}}  {'Oracle':>8}  "
            f"{'Margin':>8}  Decision"
        )
        print("  " + "-" * (col_w + 60))
        for d in results:
            flags = " ★" if d["manual_override"] else "  "
            flags += "⚠" if d["needs_review"] else " "
            path0 = d["decision_path"][0][:60] if d["decision_path"] else ""
            print(
                f"  {d['article']:<{col_w}}  "
                f"{d['oracle_arm']:<8}  "
                f"{d['margin']:>+8.4f}  "
                f"{path0}{flags}"
            )

    if not args.dry_run and results:
        print(
            f"\n  Wrote {len(results)} article_oracle.json file(s) "
            "under rl_training_data/bases/"
        )

    if errors:
        print(f"\n  {len(errors)} ERROR(s):")
        for art, msg in errors:
            print(f"    {art}: {msg}")
        sys.exit(1)


if __name__ == "__main__":
    main()
