"""Compute article-level oracles and write ``article_oracle.json`` for all 24
article-variants (8 base articles × 3 variants = 24 total).

Reads
-----
``rl_training_data/bases/<article>/section_oracle.json``  (version 2 or 3)
    Per-section, per-arm rewards computed from episode run scoring.
    Generated by ``generate_episode_oracles.py``. Version 3 (current) derives
    depth_enhancement/breadth_enhancement rewards from a count x quality curve
    (see enhancement_reward.py) rather than a raw binary grader score; this
    module is agnostic to that distinction since it only reads the already-
    computed per-arm reward floats, not the underlying grader dimensions.

``rl_training_data/bases/<article>/section_oracle_averaged.json``  (optional)
    Same shape, but each (section, arm) cell already averaged across the
    production draw + every graded ``noise_experiment/`` replicate, written
    by ``merge_replicate_oracles.py``. Used automatically instead of the
    single-draw file whenever it exists -- not a caller choice (A.16,
    2026-08-25).

``rl_training_data/bases/<article>/guideline_features.json``
    Per-section ``target_words`` (weighting).

Decision scheme
----------------
1.  Compute **R_w** -- target-words-weighted mean of per-arm rewards,
    sourced from whichever file above is available (averaged across every
    draw when replicate data exists). This is the sole oracle signal.

2.  **oracle_arm = argmax(R_w)**. ``margin`` (winner − runner-up) is compared
    against ``ARTICLE_MARGIN_NOISE_SD`` -- the corpus-measured cross-draw
    noise floor -- shrunk by ``sqrt(n_draws)``. Below this, ``needs_review``
    is flagged, but the argmax answer is still reported: no forced
    alternative decision from unvalidated heuristics (A.16, 2026-08-25,
    retiring the earlier EPS_BAND/S3/S4/S5 text-based near-tie tie-break --
    see run13_rl_grok_pipeline_analysis.md A.16 for why: averaging is the
    statistically principled way to reduce noise once real replicated reward
    data exists, and the retired signals were unvalidated syntactic proxies
    calibrated only as a single-draw-era stopgap).

3.  **Manual overrides** (see ``_MANUAL_OVERRIDES``): take absolute
    precedence over 1-2. Two categories, both still legitimate since they
    encode information R_w cannot see at all: cases needing the
    embedding-based S1 marginal-novelty signal (not implemented here) or
    direct human review, and a set of pre-2026-08-25 N=3-replication
    majority-vote corrections kept as independently-validated, not
    automatically re-derived by this refactor.

Note on S1 / S2: the marginal-novelty knee (S1) and intra-article redundancy
(S2) signals both require an embedding model and are not computed here.
For the current 24-variant training set every near-tie case where S1/S2 were
decisive is covered by the hard-coded manual overrides below.

Output schema  (article_oracle.json, version 3)
-----------------------------------------------
version               int   3
article               str   "10_memory_knowledge_access__var_standard"
variant               str   "var_minimal" | "var_standard" | "var_demanding"
computed_at           str   ISO-8601 UTC
computed_from         str   "section_oracle_averaged.json" | "section_oracle.json"
n_draws_used          int   how many draws contributed to r_w_rewards (1 = single-draw only)
oracle_arm            str   "skip" | "light" | "standard" | "deep"
oracle_arm_idx        int   0-3  (skip=0, light=1, standard=2, deep=3)
runner_up_arm         str
runner_up_arm_idx     int
margin                float oracle_r_w − runner_up_r_w
reward_spread         float max_r_w − min_r_w
r_w_rewards           dict  {arm: float}  (target-words-weighted, averaged over n_draws_used draws)
r_w_rewards_list      list  [skip, light, standard, deep]  (indexed 0-3)
decision_path         list  human-readable trace of the decision
manual_override       bool
needs_review          bool  True when margin < ARTICLE_MARGIN_NOISE_SD/sqrt(n_draws_used)
gate_diagnostics      dict|None {arm: {cp,ra,gsp: float}} mean satisficing
                      metrics per arm (None if section_oracle.json predates
                      the "diagnostics" field) -- informational only, does
                      NOT influence oracle_arm (see Part 7 S56/S57).
low_signal_flag       bool  True if any gate_diagnostics value < DIAG_LOW_SIGNAL_THRESHOLD
tied_arms             list  other arm(s) considered statistically indistinguishable from
                      oracle_arm for this article (see ``_TIED_ARMS``) -- empty for every
                      article except genuine dead-heats (e.g. Bird_Eye_Extreme). Purely
                      additive/informational: does NOT affect oracle_arm/margin/decision_path.
                      Consumers that want "either X or Y counts as a hit" (e.g.
                      evaluation/test_grok_planner.py's verdict) should treat a prediction
                      landing on oracle_arm OR any tied_arms entry as EXACT.
tied_arm_indices      list  int indices (ARM_IDX) mirroring tied_arms
n_sections            int
n_sections_with_target int
total_target_words    int
sections              list  (see _build_section_records for fields)

Usage (from research_agent_local/training/)
    python compute_article_oracle.py               # all 24 variants
    python compute_article_oracle.py --article 10_memory_knowledge_access__var_standard
    python compute_article_oracle.py --dry-run

"""

from __future__ import annotations

import argparse
import datetime
import json
import re
import statistics
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_THIS_DIR = Path(__file__).resolve().parent
_AGENT_DIR = _THIS_DIR.parent               # research_agent_local/
_REPO_ROOT = _AGENT_DIR.parent              # RL_researcher_writer_ymaxing/
_BASES_DIR = _REPO_ROOT / "rl_training_data" / "bases"

# ---------------------------------------------------------------------------
# Preset / arm constants  (mirrors _rl_preset.py)
# ---------------------------------------------------------------------------
#: Ordered arm names (action space for the RL model).
ARMS: list[str] = ["skip", "light", "standard", "deep"]

#: Arm name → 0-based ordinal index.
ARM_IDX: dict[str, int] = {a: i for i, a in enumerate(ARMS)}

#: Total number of arms.
NUM_ARMS: int = 4

# ---------------------------------------------------------------------------
# 24 training article-variants  (8 bases × 3 variants = 24)
# ---------------------------------------------------------------------------
_BASE_ARTICLES: list[str] = [
    "02_workflows_vs_agents",
    "03_context_engineering",
    "05_workflow_patterns",
    "06_tools",
    "08_react_practice",
    "09_RAG",
    "10_memory_knowledge_access",
    "11_multimodal",
]
_VARIANTS: list[str] = ["var_minimal", "var_standard", "var_demanding"]

ALL_ARTICLES: list[str] = [
    f"{base}__{var}"
    for base in _BASE_ARTICLES
    for var in _VARIANTS
]

# ---------------------------------------------------------------------------
# Decision constants
# ---------------------------------------------------------------------------
# ARTICLE_MARGIN_NOISE_SD replaces EPS_BAND/S3/S4/S5's near-tie tie-break
# (retired 2026-08-25 -- run13_rl_grok_pipeline_analysis.md A.16). Measured
# directly as the cross-draw sd of the ARTICLE-level margin itself (winner
# R_w minus runner-up R_w, both fixed by the mean across draws), pooled
# across all 40 replicated corpus articles (production + 2 replicates each,
# temp=0.7): mean=0.0540 (n=40 articles). This is the single-draw (N=1)
# noise floor; for an article whose R_w is averaged over N draws, the
# confidence threshold shrinks by sqrt(N) -- same convention as A.7/A.11's
# defensible-share analysis (an N-draw average is less noisy than one draw).
ARTICLE_MARGIN_NOISE_SD: float = 0.054

# Below this, an arm's mean cp/ra/gsp (see _compute_gate_diagnostics) is
# reported via low_signal_flag -- informational only, never affects oracle_arm.
DIAG_LOW_SIGNAL_THRESHOLD: float = 0.85

# ---------------------------------------------------------------------------
# Manual overrides
#
# Key: article variant name  →  Value: confirmed oracle arm
#
# These take absolute precedence over the mean-R_w computation (A.16,
# 2026-08-25 -- the near-tie tie-break these were originally validated
# against, EPS_BAND/S3/S4/S5, has since been retired; see this module's
# docstring). Two categories, both still legitimate since they encode
# information R_w cannot see at all:
#   · Original 2026-06-05 cases: manual review (needs_review=True or the R_w
#     winner overridden after inspection), and near-tie cases where the
#     embedding-based S1 marginal-novelty knee (not implemented in this
#     module) was decisive.
#   · 2026-08-20/25 N=3-replication majority-vote corrections (A.15.2/
#     A.15.4): derived by majority vote of each draw's own raw R_w argmax,
#     BEFORE this module's default mechanism became mean-R_w itself -- kept
#     as independently-validated corrections, not re-derived automatically
#     by this refactor.
# ---------------------------------------------------------------------------
_MANUAL_OVERRIDES: dict[str, str] = {
    # --- manual review (needs_review=True or human inspection) ---
    "06_tools__var_minimal":               "skip",
    "11_multimodal__var_demanding":        "standard",

    # --- near-tie where S1 knee was decisive (no S4/S3/S5 actionable) ---
    # NOTE: 03_context_engineering__var_minimal removed — now covered by the
    #       external_evidence_policy=forbidden → skip hard constraint.
    "09_RAG__var_demanding":               "deep",

    # --- A.15.2/A.15.4 N=3-replication majority-vote corrections (2026-08-20,
    #     A.16.7 Phase 1). Decided by the pre-registered majority-vote-of-
    #     per-draw-arm-winners rule (production + 2 replicates), which takes
    #     precedence over compute_article_oracle's own automated near-tie S3/
    #     S4/S5 tie-break precisely because that tie-break reads only ONE
    #     arm's single-draw article text and has no cross-draw evidence.
    #     Confirmed the automated decision still disagrees with these three
    #     even after the A.16.0 ordinal-index fix (--use-averaged alone picks
    #     'deep' for both 06_tools__var_demanding and 13_agent_framework via
    #     S3/S4/S5, not the majority-vote-governed 'light') -- see
    #     run13_rl_grok_pipeline_analysis.md A.15.2/A.15.4/A.16.0.
    #     (10_memory_knowledge_access__var_demanding and
    #     02_workflows_vs_agents__var_demanding needed NO override: their
    #     2026-08-16 grade correction already made the automated decision
    #     correct at the data layer.)
    "08_react_practice__var_demanding":    "light",
    "11_multimodal__var_standard":         "skip",
    "06_tools__var_demanding":             "light",
    # 2026-09-07 documentation fix: this entry also had no dedicated comment.
    #     Per-draw votes (2026-09-07 re-grade): [deep, deep, deep] -> deep
    #     (3/3 unanimous), low cross-draw variance (sd=0.021, tightest of any
    #     near-tie reviewed this session), p(2-tail)=0.021 -- the only
    #     comparison this session to clear conventional significance. `deep`
    #     is also the raw averaged-R_w argmax (margin +0.0827) by a wide
    #     margin, so this override is redundant with the uncorrected data --
    #     kept pinned for the same future-drift-protection reason as the
    #     other "not a true override" entries. See
    #     oracle_review/Earth_Oceans_Origin.md Reviewer conclusion.
    "Earth_Oceans_Origin":                 "deep",
    "Gravity_Entropy":                     "light",
    # 2026-09-02 re-scoring update: article was manually re-graded (production
    #     all 4 presets; replicate1 presets 2-3; replicate2 presets 0,1,3),
    #     margin grew from +0.0139 to +0.0209. Per-draw sign was already
    #     unanimous (3/3 favor light) both before and after; the correction
    #     strengthened significance to p=0.038 (one-tailed, df=2) -- `light`
    #     now beats every other arm (deep, skip, standard) at p<0.05
    #     one-tailed, the only near-tie article this session where that
    #     holds across all pairwise comparisons. Still not a true override --
    #     `light` remains the raw averaged-R_w argmax. See
    #     oracle_review/Gravity_Entropy.md Reviewer conclusion for the full
    #     distributional/quantitative basis.
    "13_agent_framework":                  "light",
    # 2026-09-02 re-scoring update: article was manually re-graded (production
    #     all 4 presets; replicate1 presets 2-3; replicate2 preset 0 only),
    #     margin grew from +0.0034 (weakest near-tie reviewed this session) to
    #     +0.0309 (now on par with ARTICLE_MARGIN_NOISE_SD/sqrt(3)=0.0312).
    #     The correction flipped the production draw's own winner from deep
    #     to light and made the per-draw sign unanimous (3/3 favor light,
    #     was 2/3 before) with the lowest cross-draw sd of any near-tie
    #     article reviewed (0.0135). `light` is still not a true override --
    #     it remains the raw averaged-R_w argmax. See
    #     oracle_review/13_agent_framework.md Reviewer conclusion for the
    #     full distributional/quantitative basis.
    # 2026-09-06 documentation fix: this entry previously had NO comment at
    #     all (an oversight -- every other entry documents its basis).
    #     Per-draw votes (2026-09-06 re-grade): [light, deep, deep] -> deep
    #     (2/3), but replicate1's "deep" win margin (+0.0082) is an order of
    #     magnitude smaller than production's (-0.0505) or replicate2's
    #     (+0.1344) -- a near-zero draw, not a genuinely decisive one (same
    #     caution as `Bird_Eye_Extreme`'s vote-counting lesson). `deep` is
    #     still the raw averaged-R_w argmax (margin +0.0307, p=0.630 --
    #     essentially no significance), so this override is currently
    #     redundant with the uncorrected data, not a true divergent
    #     override -- kept pinned to protect against a future re-grading
    #     nudging the raw argmax back to `light` without deliberate review.
    #     See oracle_review/Insects_Consciousness.md Reviewer conclusion for
    #     the full basis.
    "Insects_Consciousness":               "deep",

    # --- 2026-08-25: N=3 promotion for 4 TEST articles that had replicate
    #     draws in noise_experiment/ but were never merged into production
    #     (assessed MODERATE risk-tier in A.15.1, lower priority than the 12
    #     CRITICAL/HIGH articles replicated in A.15.4). Decided by the SAME
    #     majority-vote-of-per-draw-raw-argmax rule as the block above (not
    #     the averaged-R_w argmax, and not compute_article_oracle's own
    #     --use-averaged tie-break output, which the A.15.4 precedent already
    #     established as untrustworthy here since S3/S4/S5 read only the
    #     single production draft's text). Votes: 29_evaluation_metrics =
    #     [light, standard, standard] -> standard (2/3, flips); HNSW =
    #     [light, light, deep] -> light (2/3, confirms, no override needed);
    #     31_CI = [light, light, skip] -> light (2/3, confirms, no override
    #     needed); State_of_LLM_Reasoning = [skip, skip, light] -> skip (2/3,
    #     confirms, and policy-forced regardless). See A.18.6 addendum.
    # 2026-09-01 re-scoring update: article was manually re-graded (all 4
    #     presets x 3 draws), margin dropped from +0.0198 to +0.0076 (well
    #     under needs_review's own threshold -- note this manual override
    #     bypasses that check regardless of margin). Re-verified: the
    #     per-draw vote is UNCHANGED at [light, standard, standard] ->
    #     standard (2/3), and standard is still the raw averaged-R_w argmax
    #     (still not a true divergent override). But standard-vs-light is
    #     now the single weakest-evidence near-tie pair reviewed all
    #     session (one-tailed p=0.46, sd=0.117 vs mean margin 0.008) --
    #     driven by light's anomalous production-draw spike (0.492, its
    #     article-wide high) coinciding with standard's article-wide low
    #     (0.365) on that same draw. See oracle_review/29_evaluation_metrics.md
    #     Reviewer conclusion for the full distributional/quantitative basis.
    # 2026-09-02 second re-scoring update: margin grew again, +0.0076 ->
    #     +0.0165. Per-draw vote still unchanged at [light, standard,
    #     standard] -> standard (2/3). standard-vs-light is still the
    #     weakest near-tie pair reviewed (p=0.40 one-tailed, sd=0.101,
    #     nearly unchanged), still driven by the same volatile production
    #     draw (light's spike grew to 0.494). But standard's corpus-wide
    #     position strengthened: it now beats deep (p=0.041 one-tailed,
    #     3/3) and skip (p=0.043, 3/3) with conventionally-significant,
    #     unanimous evidence -- corroborating standard as the correct
    #     overall pick even though the specific runner-up pairing remains
    #     weak. See oracle_review/29_evaluation_metrics.md Reviewer
    #     conclusion (updated 2026-09-02) for full details.
    # 29_evaluation_metrics: RECLASSIFIED SOLE 2026-09-08 (was the audit
    #     counter-example that motivated retiring v1 -- see below). At N=3,
    #     margin=+0.0165 (manual override -> standard, redundant with raw
    #     argmax), per-draw (standard-light)=[-0.1004,+0.0812,+0.0688] --
    #     v1's magnitude check passed cleanly (every draw far exceeds the
    #     0.3x-tau floor, hard vote 2/3 agrees with the mean winner) yet
    #     p=0.804, a near-perfect coin flip, because the dissenting draw
    #     (-0.1004) is itself the LARGEST in magnitude, driving sd up to
    #     0.101 -- this is what motivated retiring v1 and moving to a direct
    #     p-value check (v2). Real replicate expansion since then: N=5
    #     (2026-09-08, replicate3/replicate4 merged) dropped p to 0.355 --
    #     still MULTIPLE, but already less than half the N=3 value. N=7
    #     (2026-09-08, replicate5/replicate6 merged, real data not a
    #     projection) drops it further: per-draw (standard-light)=
    #     [-0.0779,+0.0812,+0.0688,+0.0084,+0.0787,+0.0300,+0.0754], mean
    #     +0.0378, sd=0.0581, t=+1.723 (df=6), **p=0.136** -- now clears the
    #     v2 ALPHA=0.20 threshold. `standard` stays oracle_arm (override
    #     preserved, and still coincides with the raw argmax); `light` is no
    #     longer registered as tied. See oracle_review/29_evaluation_metrics.md
    #     Reviewer conclusion (2026-09-08, N=7) for the full basis.
    "29_evaluation_metrics":               "standard",
    # --- 2026-08-27 override REVOKED 2026-09-06: near-tie oracle review
    #     battery, distributional override (A.19), originally justified by
    #     mean-R_w argmax picking `deep` for HNSW (margin +0.0343) despite an
    #     extreme 8.19x sd ratio (deep sd=0.136 vs light sd=0.017) AND clean
    #     maximin dominance (2 of deep's 3 draws fell entirely below light's
    #     observed range). A full re-grading round (2026-09-06) erased BOTH
    #     conditions the override depended on: new per-draw R_w deep=[0.475,
    #     0.374, 0.633] (sd=0.130) vs light=[0.316, 0.525, 0.436] (sd=0.105)
    #     -- sd ratio now only 1.24x (not 8.19x), and deep's minimum (0.374)
    #     sits INSIDE light's range [0.316, 0.525], i.e. zero maximin
    #     dominance remains. Raw mean-R_w argmax is now `deep` by a much
    #     wider, unambiguous margin (+0.0681, roughly 2x the original), with
    #     a 2/3 per-draw majority also favoring deep (production, replicate2)
    #     against only replicate1 favoring light. Quantitatively deep now
    #     leads on cc/de/be/ga (previously only de/be/ga, with cc slightly
    #     favoring light) -- deep's advantage is broader, not narrower, after
    #     correction. Since the override's own stated justification no
    #     longer holds on the corrected data, it has been removed; oracle_arm
    #     reverts to the raw mean-R_w argmax (`deep`). See
    #     oracle_review/HNSW.md Reviewer conclusion (2026-09-06) for the full
    #     before/after comparison.
}

# ---------------------------------------------------------------------------
# Tied arms (see ``tied_arms`` in the schema docstring above)
#
# Purely additive/informational -- does NOT affect oracle_arm, margin, or
# decision_path in any way. Populated only for articles independently
# reviewed and found to be a genuine dead heat between two arms (not merely
# a thin margin -- see the article's own oracle_review/<article>.md for the
# distributional basis establishing this).
# ---------------------------------------------------------------------------
_TIED_ARMS: dict[str, list[str]] = {
    # 2026-09-05: light vs standard genuine tie (see the CONSIDERED-AND-
    #     DECLINED override note in _MANUAL_OVERRIDES above). Per-draw margins
    #     (light-standard) are [+0.0787, -0.0566, -0.0023] -- only 1 real win
    #     each plus one statistical wash, not a real 2/3 majority either way.
    #     `oracle_arm` stays `light` (raw mean-R_w argmax, no override), but
    #     `standard` is registered here as an equally valid pick. p=0.882
    #     under the v2 (p-value) rule below -- confirmed MULTIPLE.
    "Bird_Eye_Extreme": ["standard"],
    # 2026-09-05: skip vs deep genuine tie. Whole-article reward landscape
    #     compressed after a full re-grade (reward_spread=0.040, tightest in
    #     the corpus); oracle_arm=deep by margin=+0.0007 (~44x below the
    #     noise threshold). Per-draw margins (skip-deep) are [-0.0026,
    #     -0.0071, +0.0076] -- 2/3 draws favor deep but every margin is
    #     comparably tiny, p=0.887 (near-coin-flip, confirmed MULTIPLE under
    #     the v2 rule below). Mechanism: deep's real de/be content-enrichment
    #     gain is almost exactly offset by its ga (guideline-adherence) cost
    #     -- see oracle_review/07_reasoning_planning.md for the full basis.
    "07_reasoning_planning": ["skip"],
    # Dark_Dimension: TIED-ARMS ENTRY REMOVED 2026-09-09 (was ["standard"]).
    #     At N=3 (2026-09-07, v1 rule): margin=+0.0193, per-draw
    #     (deep-standard)=[-0.0756,+0.1694,-0.036] -- hard vote favored
    #     standard 2/3, DISAGREEING with mean winner deep (deep's only win,
    #     replicate1, was a large outlier); p=0.823, confirmed MULTIPLE.
    #     Real replicate expansion to N=8 (2026-09-09, replicate2-7 merged,
    #     real data not a projection) resolved this: runner-up flipped
    #     standard->light (R_w light=0.515 now edges out standard=0.507),
    #     and BOTH near-contenders clear the v2 ALPHA=0.20 threshold --
    #     deep-vs-light per-draw=[+0.0701,+0.1457,+0.0182,+0.0009,-0.0346,
    #     -0.0379,+0.0294,+0.0665], mean+0.0323, p=0.178, 6/8 favor deep;
    #     deep-vs-standard per-draw=[-0.0756,+0.1694,-0.016,+0.0557,+0.0843,
    #     +0.0229,+0.0408,+0.0423], mean+0.0405, p=0.153, 6/8 favor deep.
    #     `deep` reclassifies SOLE -- no arm remains registered as tied. See
    #     oracle_review/Dark_Dimension.md Reviewer conclusion (2026-09-09,
    #     N=8) for the full basis.
    # Distinct_AI_Models: margin=+0.0180, per-draw (light-standard)=
    #     [+0.0009,-0.0119,+0.0649], p=0.529 -- confirmed MULTIPLE under the
    #     v2 (p-value) rule below.
    "Distinct_AI_Models": ["standard"],
    # Insects_Consciousness: margin=+0.0307 (manual override, redundant with
    #     raw argmax), per-draw (deep-light)=[-0.0505,+0.0082,+0.1344],
    #     p=0.630 -- confirmed MULTIPLE under the v2 (p-value) rule below.
    "Insects_Consciousness": ["light"],
    # 2026-09-07 v2 additions: rule replaced with a direct p-value check
    # (see MULTI_ORACLE_RULE below) -- these 4 were "sole" under the retired
    # v1 margin/hard-vote-magnitude heuristic but their own t-test says
    # otherwise; a concrete audit example (29_evaluation_metrics, below)
    # showed v1 could pass an article whose per-draw margins were all large
    # in magnitude yet still statistically indistinguishable from a tie,
    # because the DISSENTING draw was itself large, inflating variance --
    # v1's "no draw negligibly small" check only guarded against the
    # opposite failure mode.
    # 04_structured_outputs: N=5 UPDATE (2026-09-09) -- the raw mean-R_w
    #     argmax itself FLIPPED deep->standard (was margin=+0.0711 favoring
    #     deep at N=3, cleared v1's margin>tau bar outright; now margin=
    #     +0.0183 favoring standard, oracle_arm/runner_up_arm swapped). The
    #     underlying toss-up is UNCHANGED, just relabeled: per-draw (standard-
    #     deep)=[-0.0026,+0.0232,-0.0740,+0.0320,+0.1131], p=0.576 (was 0.249
    #     at N=3, i.e. got LESS decisive, not more, with 2 more real draws) --
    #     still confirmed MULTIPLE under v2. `deep` (now the runner-up)
    #     replaces `standard` as the registered tied arm below.
    "04_structured_outputs": ["deep"],
    # 31_CI: margin=+0.0150, per-draw (light-skip)=[+0.0382,+0.038,-0.0312],
    #     p=0.582 (v1 called this SOLE via the hard-vote/magnitude branch --
    #     all 3 draws individually non-negligible, but their sign disagrees
    #     2-1 with a full-magnitude dissenting draw, hence p=0.582 not <0.05).
    "31_CI": ["skip"],
    # HNSW: margin=+0.0681 (cleared v1's margin>tau bar outright, the same
    #     branch that let 04_structured_outputs and Earth_Oceans_Origin
    #     through unconditionally), per-draw (deep-light)=
    #     [+0.1587,-0.1508,+0.1963], p=0.599 -- large swings both directions,
    #     cross-draw sd=0.191 (highest in the corpus) swamps the mean.
    "HNSW": ["light"],
    # 29_evaluation_metrics: TIED-ARMS ENTRY REMOVED 2026-09-08 (was
    #     ["light"]). THE audit counter-example that originally motivated
    #     retiring v1 (at N=3, margin=+0.0165, per-draw (standard-light)=
    #     [-0.1004,+0.0812,+0.0688], p=0.804 -- a near-perfect coin flip
    #     despite every draw individually clearing v1's magnitude floor).
    #     Real replicate expansion since then (N=5, then N=7, both real
    #     data not projections -- see the `_MANUAL_OVERRIDES` entry above
    #     for the full per-draw numbers) dropped p to 0.355 then 0.136,
    #     crossing below the v2 ALPHA=0.20 threshold. Per the v2 rule this
    #     article now reclassifies SOLE -- `light` removed from
    #     `_TIED_ARMS`. See oracle_review/29_evaluation_metrics.md Reviewer
    #     conclusion (2026-09-08, N=7) for the full basis.
    # State_of_LLM_Reasoning: CONSIDERED AND DECLINED (2026-09-07). Margin=
    #     +0.0033, per-draw (skip-light)=[+0.0334,-0.0242,+0.0008], p=0.861
    #     -- mechanically qualifies as MULTIPLE under BOTH the retired v1
    #     rule and the current v2 (p-value) rule. NOT applied: this
    #     article's own enhancement-instance analysis found a *structural*,
    #     not just statistical, reason skip should win -- `light`'s
    #     exploration payoff (0.45*de+0.30*be) tops out at 0.029 even at
    #     full saturation (replicate2, the maximum possible instance credit),
    #     still short of `skip`'s deterministic 0.030 cost advantage
    #     (`-0.03*nr`). That makes replicate2's near-zero margin a real
    #     structural ceiling, not statistical noise -- so `skip` is the sole
    #     oracle here regardless of which classification rule is applied.
    #     See oracle_review/State_of_LLM_Reasoning.md Reviewer conclusion.
}

# ---------------------------------------------------------------------------
# Multi-oracle classification rule v2 (2026-09-07 -- REPLACES the same-day
# margin/hard-vote-magnitude v1 rule after an internal audit found it didn't
# track actual statistical confidence; formalizes/extends the ad hoc
# majority-vote rule already used for the A.15.2/A.15.4 manual overrides
# above)
#
# RULE: compute the per-draw margins margin_i = R_w[oracle_arm] -
# R_w[runner_up_arm] for the 3 draws (production/replicate1/replicate2), then
# the two-tailed p-value of a paired t-test (df=2, Student-t closed form
# F(t)=0.5*(1+t/sqrt(2+t^2))) against the null that the true mean margin is 0
# (see analyze_near_tie_metrics.distributional_basis, already computes this).
#   p < ALPHA (0.20) -> SOLE oracle = oracle_arm.
#   p >= ALPHA        -> MULTIPLE oracles: register runner_up_arm in
#                        _TIED_ARMS -- UNLESS a separate, article-specific
#                        mechanistic analysis (e.g. an enhancement-instance/
#                        reward-formula breakdown showing one arm
#                        structurally cannot beat the other even in its
#                        best-case draw) positively explains the result as a
#                        real ceiling rather than noise, in which case the
#                        article stays SOLE (State_of_LLM_Reasoning is the
#                        only case this exception has applied to so far).
#
# ALPHA=0.20 (not the conventional 0.05): with n_draws=3 (df=2), the
# two-tailed critical value for p<0.05 is |t|>4.303 -- an extremely high bar
# that only 1 of 16 TEST articles ever clears (Earth_Oceans_Origin, p=0.021).
# N=3 is a deliberate budget-vs-robustness compromise, not a design that can
# support conventional significance thresholds; 0.20 (|t|>1.886) was chosen
# both for this power reason and because it falls in a natural gap in the
# corpus's actual p-value distribution -- 6 articles cluster at p<=0.196,
# the next-nearest sits at p=0.249, a comfortable margin either side of the
# cutoff. Note Understanding_Reasoning_LLMs (p=0.196) sits close enough to
# this boundary that a stricter alpha (e.g. 0.15) would flip it to MULTIPLE.
#
# WHY v1 (margin > ARTICLE_MARGIN_NOISE_SD/sqrt(n_draws), or a per-draw
# "not-negligible" magnitude floor as a fallback) was RETIRED: margin > tau
# alone doesn't track this article's own measured noise at all -- tau is a
# POOLED, corpus-wide constant (single-draw sd=0.054), while actual per-
# article cross-draw sd ranges from 0.011 to 0.191, almost a 20x spread.
# Of the 6 articles v1 called "confident sole" purely via margin>tau, 5 have
# p>0.15 by their OWN data (04_structured_outputs p=0.249, 14_agent_system_
# design p=0.164, HNSW p=0.599, Space-Time_QECC p=0.154, Understanding_
# Reasoning_LLMs p=0.196) -- only Earth_Oceans_Origin (p=0.021) was genuinely
# confident. The per-draw magnitude fallback has its own blind spot, caught
# by 29_evaluation_metrics: every draw clears the "not negligible" floor
# (none is small) yet p=0.804, because the fallback only guards against
# winning draws being too small, not against the DISSENTING draw being large
# enough to blow up the variance.
#
# Retroactively re-validated against all 16 TEST articles' article_oracle.json
# (2026-09-07 audit, all fresh from that day's re-grade) under this v2 rule:
# 6 SOLE (Earth_Oceans_Origin p=0.021, Gravity_Entropy p=0.075,
# 13_agent_framework p=0.084, Space-Time_QECC p=0.154, 14_agent_system_design
# p=0.164, Understanding_Reasoning_LLMs p=0.196 -- 2 of these are also
# _MANUAL_OVERRIDES, both still the raw argmax regardless), 9 MULTIPLE (all
# entries in _TIED_ARMS above), 1 exception (State_of_LLM_Reasoning, stays
# SOLE via the mechanistic-ceiling override).
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# File loaders
# ---------------------------------------------------------------------------

def _load_section_oracle(article: str, use_averaged: bool = False) -> dict:
    """Load and validate section_oracle.json (v2+) for *article*.

    ``use_averaged=True`` loads the sibling ``section_oracle_averaged.json``
    (written by merge_replicate_oracles.py) instead -- its own "version" field
    numbers the merge format, not the section_oracle.json schema, so the v2+
    check is skipped for it.
    """
    fname = "section_oracle_averaged.json" if use_averaged else "section_oracle.json"
    path = _BASES_DIR / article / fname
    if not path.exists():
        raise FileNotFoundError(f"{fname} not found for '{article}'")
    data = json.loads(path.read_text(encoding="utf-8"))
    if not use_averaged:
        v = data.get("version", 1)
        if v < 2:
            raise ValueError(
                f"section_oracle.json for '{article}' is version {v}; "
                "version 2+ required. Re-run generate_episode_oracles.py."
            )
    if not data.get("sections"):
        raise ValueError(f"{fname} for '{article}' has no sections.")
    return data


def _load_guideline_features(article: str) -> dict:
    """Load guideline_features.json for *article*."""
    path = _BASES_DIR / article / "guideline_features.json"
    return json.loads(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# R_w  (target-words-weighted mean of per-arm section rewards)
# ---------------------------------------------------------------------------

def _compute_r_w(
    oracle_sections: dict[str, dict],
    features_sections: dict[str, dict],
) -> tuple[dict[str, float], int, int, int]:
    """Return (r_w_per_arm, total_target_words, n_sections, n_with_target).

    oracle_sections  : section_oracle.json["sections"]  {sec_id: {oracle, rewards, explore?}}
    features_sections: guideline_features.json["sections"]  {sec_id: {target_words, …}}

    As of section_oracle.json version 4, each section may carry an "explore"
    sub-dict (per-arm) alongside "rewards" (per-arm, unchanged full total).
    When present, this function aggregates the two pieces DIFFERENTLY:
      - "rewards - explore" (i.e. gt_base + user_intent + cost) is averaged
        target-words-weighted, as before -- a section assigned a bigger word
        budget legitimately deserves more say over the article's overall
        content-quality/adherence/cost verdict.
      - "explore" is averaged with a SIMPLE (unweighted) mean across sections
        -- a genuinely valuable enhancement instance shouldn't count for more
        or less just because it happened to land in a long vs short section.
        See run13_rl_grok_pipeline_analysis.md Part 5 for the real-corpus case
        (13_agent_framework) that motivated this: `deep`'s enhancement
        instances were spread thin across many sections while `standard`
        concentrated instances into one heavily-weighted section, letting
        `standard` win on weight alone.
    R_w[arm] = weighted_mean(rewards[arm] - explore[arm], weights=target_words)
               + simple_mean(explore[arm])

    For version 2/3 data (no "explore" field), falls back EXACTLY to the old
    pure target-words-weighted mean of the combined "rewards" value -- zero
    behaviour change for un-migrated section_oracle.json files.
    """
    arm_acc_rest: dict[str, float] = {a: 0.0 for a in ARMS}
    arm_acc_explore: dict[str, float] = {a: 0.0 for a in ARMS}
    total_w = 0
    n_sections = 0
    n_with_target = 0
    has_explore_field = False

    for sec_id, info in oracle_sections.items():
        rewards = info["rewards"]                          # {skip, light, standard, deep}
        explore = info.get("explore")                       # v4+ only; None for v2/v3
        feat = features_sections.get(sec_id, {})
        tw_val = feat.get("target_words")
        tw = int(tw_val) if tw_val is not None else 100   # fallback weight
        if tw_val is not None:
            n_with_target += 1
        total_w += tw
        n_sections += 1

        for arm in ARMS:
            total_reward = float(rewards.get(arm, 0.0))
            if explore is not None:
                has_explore_field = True
                explore_val = float(explore.get(arm, 0.0))
                arm_acc_rest[arm] += tw * (total_reward - explore_val)
                arm_acc_explore[arm] += explore_val
            else:
                arm_acc_rest[arm] += tw * total_reward

    if total_w == 0:
        return {a: 0.0 for a in ARMS}, 0, len(oracle_sections), n_with_target

    if has_explore_field:
        r_w = {
            a: (arm_acc_rest[a] / total_w) + (arm_acc_explore[a] / n_sections)
            for a in ARMS
        }
    else:
        r_w = {a: arm_acc_rest[a] / total_w for a in ARMS}
    return r_w, total_w, n_sections, n_with_target


def _compute_gate_diagnostics(
    oracle_sections: dict[str, dict],
) -> dict[str, dict[str, float]] | None:
    """Per-arm simple mean of cp/ra/gsp across sections (unweighted -- these
    are satisficing checks, not content-value signals). Returns None when
    section_oracle.json predates the "diagnostics" field (v<5).
    """
    sums = {a: {"cp": 0.0, "ra": 0.0, "gsp": 0.0} for a in ARMS}
    n = 0
    for info in oracle_sections.values():
        diag = info.get("diagnostics")
        if diag is None:
            return None
        n += 1
        for a in ARMS:
            for k in ("cp", "ra", "gsp"):
                sums[a][k] += diag[a][k]
    if n == 0:
        return None
    return {a: {k: round(v / n, 6) for k, v in sums[a].items()} for a in ARMS}


# ---------------------------------------------------------------------------
# Oracle decision
# ---------------------------------------------------------------------------

def _decide(
    article: str,
    r_w: dict[str, float],
    n_draws: int = 1,
    external_evidence_policy: str = "allowed",
) -> tuple[str, bool, bool, list[str], list[str]]:
    """Return (oracle_arm, manual_override, needs_review, decision_path, candidate_arms).

    Pure mean-R_w argmax (A.16, 2026-08-25) -- retires the EPS_BAND/S3/S4/S5
    near-tie tie-break entirely. ``r_w`` is expected to already be the mean
    across every available draw (production + replicates, via
    section_oracle_averaged.json when it exists); ``n_draws`` says how many
    contributed, so the confidence check can shrink ARTICLE_MARGIN_NOISE_SD
    by sqrt(n_draws) -- an averaged margin is less noisy than a single draw's.

    ``candidate_arms`` is the arm set the decision actually searched over --
    ARMS unless policy=="capped" restricts it to ["skip", "light"] (A.20) --
    so the caller's runner-up/margin bookkeeping can stay scoped to the same
    set instead of always comparing against arms the policy ruled out.
    """
    # -1. Hard constraint: forbidden policy → skip, regardless of R_w.
    #     External evidence cannot be used in the final article, so the only
    #     valid production choice is the no-exploration arm.
    if external_evidence_policy == "forbidden":
        return "skip", False, False, ["policy=forbidden → skip (hard constraint)"], ARMS

    # 0.  Manual override: absolute precedence over the mean-R_w computation.
    if article in _MANUAL_OVERRIDES:
        arm = _MANUAL_OVERRIDES[article]
        return arm, True, False, [f"manual override → {arm}"], ARMS

    # Scenario C (A.20): article's own stated scope is a survey/exploitation
    # task, not a hard ban -- cap the decision to {skip, light}, never
    # standard/deep, without forcing a single fixed answer the way forbidden does.
    candidate_arms = ["skip", "light"] if external_evidence_policy == "capped" else ARMS

    ranked = sorted(candidate_arms, key=lambda a: r_w[a], reverse=True)
    best_arm = ranked[0]
    margin = r_w[best_arm] - r_w[ranked[1]]
    threshold = ARTICLE_MARGIN_NOISE_SD / (n_draws ** 0.5)
    needs_review = margin < threshold
    path = [
        f"mean R_w argmax over {n_draws} draw(s), policy={external_evidence_policy} "
        f"(candidates={candidate_arms}): {best_arm}  "
        f"margin={margin:+.4f}  1x-noise-sd threshold={threshold:.4f}  "
        f"{'BELOW threshold, low confidence' if needs_review else 'confident'}"
    ]
    return best_arm, False, needs_review, path, candidate_arms


# ---------------------------------------------------------------------------
# Build per-section output records
# ---------------------------------------------------------------------------

def _sec_id_to_title(sec_id: str) -> str:
    """Convert 'S3::section-3-choosing-your-path' → 'choosing your path'."""
    m = re.match(r"S\d+::section-\d+-(.+)$", sec_id)
    return m.group(1).replace("-", " ") if m else sec_id


def _build_section_records(
    oracle_sections: dict[str, dict],
    features_sections: dict[str, dict],
    total_target_words: int,
) -> list[dict]:
    records = []
    for i, (sec_id, info) in enumerate(oracle_sections.items()):
        rewards = info["rewards"]
        feat = features_sections.get(sec_id, {})
        tw_val = feat.get("target_words")
        tw = int(tw_val) if tw_val is not None else 100
        weight_frac = round(tw / total_target_words, 5) if total_target_words > 0 else 0.0

        sec_ranked = sorted(ARMS, key=lambda a: float(rewards.get(a, 0.0)), reverse=True)
        records.append({
            "index": i + 1,
            "sec_id": sec_id,
            "title": _sec_id_to_title(sec_id),
            "target_words": tw_val,
            "weight_words": tw,
            "weight_frac": weight_frac,
            # rewards keyed by arm name
            "rewards": {a: round(float(rewards.get(a, 0.0)), 6) for a in ARMS},
            # rewards as a list indexed 0=skip, 1=light, 2=standard, 3=deep
            # used by analyze_eval_results.py for section reward-gap analysis
            "rewards_by_preset": [
                round(float(rewards.get(a, 0.0)), 6) for a in ARMS
            ],
            "section_oracle": info.get("oracle", sec_ranked[0]),
            "section_oracle_idx": ARM_IDX.get(info.get("oracle", sec_ranked[0]), 0),
        })
    return records


# ---------------------------------------------------------------------------
# Main per-variant computation
# ---------------------------------------------------------------------------

def _variant_of(article: str) -> str:
    if "__var_minimal" in article:
        return "var_minimal"
    if "__var_demanding" in article:
        return "var_demanding"
    if "__var_standard" in article:
        return "var_standard"
    return "no_variant"  # no-variant test articles


def compute_article_oracle(article: str) -> dict:
    """Compute the full article-level oracle record for one variant.

    Sources R_w from ``section_oracle_averaged.json`` (mean across production
    + every graded replicate) whenever it exists, falling back to the
    single-draw ``section_oracle.json`` otherwise -- automatic, not a caller
    choice (A.16, 2026-08-25). This retires the earlier canonical-vs-
    ``_averaged``-sibling-file split entirely: there is no remaining reason
    to privilege the single production draw once more draws are available.

    Returns a dict ready for JSON serialisation matching the schema in
    this module's docstring.
    """
    # --- load inputs ---
    use_averaged = (_BASES_DIR / article / "section_oracle_averaged.json").exists()
    oracle_data = _load_section_oracle(article, use_averaged=use_averaged)
    oracle_sections: dict[str, dict] = oracle_data["sections"]
    n_draws = oracle_data.get("n_draws_per_arm", 1) if use_averaged else 1

    feat_data = _load_guideline_features(article)
    features_sections: dict[str, dict] = feat_data.get("sections", {})

    # --- R_w ---
    r_w, total_tw, n_sections, n_with_target = _compute_r_w(
        oracle_sections, features_sections
    )

    # --- decision ---
    oracle_arm, manual_override, needs_review, decision_path, candidate_arms = _decide(
        article, r_w, n_draws=n_draws,
        external_evidence_policy=feat_data.get("external_evidence_policy", "allowed"),
    )
    oracle_arm_idx = ARM_IDX[oracle_arm]

    # Scoped to candidate_arms so a capped article's runner-up/margin reflects
    # the actual skip-vs-light decision, not an out-of-scope standard/deep arm.
    runner_up_arm = max(
        (a for a in candidate_arms if a != oracle_arm), key=lambda a: r_w[a]
    )
    runner_up_arm_idx = ARM_IDX[runner_up_arm]
    margin = r_w[oracle_arm] - r_w[runner_up_arm]
    reward_spread = max(r_w.values()) - min(r_w.values())

    # --- section records ---
    section_records = _build_section_records(
        oracle_sections, features_sections, total_tw
    )

    gate_diagnostics = _compute_gate_diagnostics(oracle_sections)
    low_signal_flag = gate_diagnostics is not None and any(
        gate_diagnostics[a][k] < DIAG_LOW_SIGNAL_THRESHOLD
        for a in ARMS
        for k in ("cp", "ra", "gsp")
    )

    tied_arms = _TIED_ARMS.get(article, [])

    return {
        "version": 3,
        "article": article,
        "variant": _variant_of(article),
        "computed_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "computed_from": "section_oracle_averaged.json" if use_averaged else "section_oracle.json",
        "n_draws_used": n_draws,
        "oracle_arm": oracle_arm,
        "oracle_arm_idx": oracle_arm_idx,
        "runner_up_arm": runner_up_arm,
        "runner_up_arm_idx": runner_up_arm_idx,
        "margin": round(margin, 6),
        "reward_spread": round(reward_spread, 6),
        "r_w_rewards": {a: round(r_w[a], 6) for a in ARMS},
        "r_w_rewards_list": [round(r_w[a], 6) for a in ARMS],
        "decision_path": decision_path,
        "manual_override": manual_override,
        "needs_review": needs_review,
        "gate_diagnostics": gate_diagnostics,
        "low_signal_flag": low_signal_flag,
        "tied_arms": tied_arms,
        "tied_arm_indices": [ARM_IDX[a] for a in tied_arms],
        "n_sections": n_sections,
        "n_sections_with_target": n_with_target,
        "total_target_words": total_tw,
        "sections": section_records,
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Compute article-level oracles from section_oracle.json v2 "
            "and write article_oracle.json for all 24 training variants."
        )
    )
    parser.add_argument(
        "--article",
        type=str,
        default=None,
        metavar="NAME",
        help="Process a single article-variant (default: all 24).",
    )
    parser.add_argument(
        "--articles",
        nargs="+",
        metavar="NAME",
        help="Process one or more article-variants (space-separated).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print results to stdout; do not write any files.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing article_oracle.json files (default: skip if already present).",
    )
    parser.add_argument(
        "--bases-dir",
        type=Path,
        default=None,
        help="Override the bases root (default: production rl_training_data/bases/). "
             "Must match generate_episode_oracles.py's --bases-dir for the same experiment.",
    )
    args = parser.parse_args()

    if args.bases_dir is not None:
        global _BASES_DIR
        _BASES_DIR = args.bases_dir

    if args.articles:
        targets = args.articles
    elif args.article:
        targets = [args.article]
    else:
        targets = ALL_ARTICLES

    mode = "DRY-RUN" if args.dry_run else ("FORCE" if args.force else "WRITE")
    print(
        f"compute_article_oracle.py  [{mode}]  "
        f"4-arm scheme (skip/light/standard/deep)\n"
        f"  Targets: {len(targets)} article-variant(s)\n"
    )

    results: list[dict] = []
    errors: list[tuple[str, str]] = []

    for article in targets:
        try:
            print(f"  {article} ...", end=" ", flush=True)
            data = compute_article_oracle(article)
            results.append(data)

            flag = " ★OVERRIDE" if data["manual_override"] else ""
            flag += " ⚠REVIEW" if data["needs_review"] else ""
            flag += " ⚑LOWSIG" if data["low_signal_flag"] else ""
            r_w_str = "  ".join(
                f"{a}={data['r_w_rewards'][a]:.3f}" for a in ARMS
            )
            print(
                f"oracle={data['oracle_arm']:<8}  "
                f"margin={data['margin']:+.4f}  "
                f"R_w=[{r_w_str}]{flag}"
            )

            if not args.dry_run:
                out_path = _BASES_DIR / article / "article_oracle.json"
                if out_path.exists() and not args.force:
                    print(f"  SKIP (already exists; use --force to overwrite): {out_path.name}")
                else:
                    out_path.write_text(
                        json.dumps(data, indent=2), encoding="utf-8"
                    )

        except Exception as exc:
            print(f"  ERROR: {exc}")
            errors.append((article, str(exc)))

    # --- summary table ---
    if results:
        col_w = max(len(d["article"]) for d in results) + 2
        print()
        print(
            f"  {'Article':<{col_w}}  {'Oracle':>8}  "
            f"{'Margin':>8}  Decision"
        )
        print("  " + "-" * (col_w + 60))
        for d in results:
            flags = " ★" if d["manual_override"] else "  "
            flags += "⚠" if d["needs_review"] else " "
            flags += "⚑" if d["low_signal_flag"] else " "
            path0 = d["decision_path"][0][:60] if d["decision_path"] else ""
            print(
                f"  {d['article']:<{col_w}}  "
                f"{d['oracle_arm']:<8}  "
                f"{d['margin']:>+8.4f}  "
                f"{path0}{flags}"
            )

    if not args.dry_run and results:
        print(
            f"\n  Wrote {len(results)} article_oracle.json file(s) "
            f"under rl_training_data/bases/{'  (--force active)' if args.force else ''}"
        )

    if errors:
        print(f"\n  {len(errors)} ERROR(s):")
        for art, msg in errors:
            print(f"    {art}: {msg}")
        sys.exit(1)


if __name__ == "__main__":
    main()
