"""Compute article-level oracles and write ``article_oracle.json`` for all 24
article-variants (8 base articles × 3 variants = 24 total).

Reads
-----
``rl_training_data/bases/<article>/section_oracle.json``  (version 2 or 3)
    Per-section, per-arm rewards computed from episode run scoring.
    Generated by ``generate_episode_oracles.py``. Version 3 (current) derives
    depth_enhancement/breadth_enhancement rewards from a count x quality curve
    (see enhancement_reward.py) rather than a raw binary grader score; this
    module is agnostic to that distinction since it only reads the already-
    computed per-arm reward floats, not the underlying grader dimensions.

``rl_training_data/bases/<article>/section_oracle_averaged.json``  (optional)
    Same shape, but each (section, arm) cell already averaged across the
    production draw + every graded ``noise_experiment/`` replicate, written
    by ``merge_replicate_oracles.py``. Used automatically instead of the
    single-draw file whenever it exists -- not a caller choice (A.16,
    2026-08-25).

``rl_training_data/bases/<article>/guideline_features.json``
    Per-section ``target_words`` (weighting).

Decision scheme
----------------
1.  Compute **R_w** -- target-words-weighted mean of per-arm rewards,
    sourced from whichever file above is available (averaged across every
    draw when replicate data exists). This is the sole oracle signal.

2.  **oracle_arm = argmax(R_w)**. ``margin`` (winner − runner-up) is compared
    against ``ARTICLE_MARGIN_NOISE_SD`` -- the corpus-measured cross-draw
    noise floor -- shrunk by ``sqrt(n_draws)``. Below this, ``needs_review``
    is flagged, but the argmax answer is still reported: no forced
    alternative decision from unvalidated heuristics (A.16, 2026-08-25,
    retiring the earlier EPS_BAND/S3/S4/S5 text-based near-tie tie-break --
    see run13_rl_grok_pipeline_analysis.md A.16 for why: averaging is the
    statistically principled way to reduce noise once real replicated reward
    data exists, and the retired signals were unvalidated syntactic proxies
    calibrated only as a single-draw-era stopgap).

3.  **Manual overrides** (see ``_MANUAL_OVERRIDES``): take absolute
    precedence over 1-2. Two categories, both still legitimate since they
    encode information R_w cannot see at all: cases needing the
    embedding-based S1 marginal-novelty signal (not implemented here) or
    direct human review, and a set of pre-2026-08-25 N=3-replication
    majority-vote corrections kept as independently-validated, not
    automatically re-derived by this refactor.

Note on S1 / S2: the marginal-novelty knee (S1) and intra-article redundancy
(S2) signals both require an embedding model and are not computed here.
For the current 24-variant training set every near-tie case where S1/S2 were
decisive is covered by the hard-coded manual overrides below.

Output schema  (article_oracle.json, version 3)
-----------------------------------------------
version               int   3
article               str   "10_memory_knowledge_access__var_standard"
variant               str   "var_minimal" | "var_standard" | "var_demanding"
computed_at           str   ISO-8601 UTC
computed_from         str   "section_oracle_averaged.json" | "section_oracle.json"
n_draws_used          int   how many draws contributed to r_w_rewards (1 = single-draw only)
oracle_arm            str   "skip" | "light" | "standard" | "deep"
oracle_arm_idx        int   0-3  (skip=0, light=1, standard=2, deep=3)
runner_up_arm         str
runner_up_arm_idx     int
margin                float oracle_r_w − runner_up_r_w
reward_spread         float max_r_w − min_r_w
r_w_rewards           dict  {arm: float}  (target-words-weighted, averaged over n_draws_used draws)
r_w_rewards_list      list  [skip, light, standard, deep]  (indexed 0-3)
decision_path         list  human-readable trace of the decision
manual_override       bool
needs_review          bool  True when margin < ARTICLE_MARGIN_NOISE_SD/sqrt(n_draws_used)
gate_diagnostics      dict|None {arm: {cp,ra,gsp: float}} mean satisficing
                      metrics per arm (None if section_oracle.json predates
                      the "diagnostics" field) -- informational only, does
                      NOT influence oracle_arm (see Part 7 S56/S57).
low_signal_flag       bool  True if any gate_diagnostics value < DIAG_LOW_SIGNAL_THRESHOLD
n_sections            int
n_sections_with_target int
total_target_words    int
sections              list  (see _build_section_records for fields)

Usage (from research_agent_local/training/)
    python compute_article_oracle.py               # all 24 variants
    python compute_article_oracle.py --article 10_memory_knowledge_access__var_standard
    python compute_article_oracle.py --dry-run

"""

from __future__ import annotations

import argparse
import datetime
import json
import re
import statistics
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_THIS_DIR = Path(__file__).resolve().parent
_AGENT_DIR = _THIS_DIR.parent               # research_agent_local/
_REPO_ROOT = _AGENT_DIR.parent              # RL_researcher_writer_ymaxing/
_BASES_DIR = _REPO_ROOT / "rl_training_data" / "bases"

# ---------------------------------------------------------------------------
# Preset / arm constants  (mirrors _rl_preset.py)
# ---------------------------------------------------------------------------
#: Ordered arm names (action space for the RL model).
ARMS: list[str] = ["skip", "light", "standard", "deep"]

#: Arm name → 0-based ordinal index.
ARM_IDX: dict[str, int] = {a: i for i, a in enumerate(ARMS)}

#: Total number of arms.
NUM_ARMS: int = 4

# ---------------------------------------------------------------------------
# 24 training article-variants  (8 bases × 3 variants = 24)
# ---------------------------------------------------------------------------
_BASE_ARTICLES: list[str] = [
    "02_workflows_vs_agents",
    "03_context_engineering",
    "05_workflow_patterns",
    "06_tools",
    "08_react_practice",
    "09_RAG",
    "10_memory_knowledge_access",
    "11_multimodal",
]
_VARIANTS: list[str] = ["var_minimal", "var_standard", "var_demanding"]

ALL_ARTICLES: list[str] = [
    f"{base}__{var}"
    for base in _BASE_ARTICLES
    for var in _VARIANTS
]

# ---------------------------------------------------------------------------
# Decision constants
# ---------------------------------------------------------------------------
# ARTICLE_MARGIN_NOISE_SD replaces EPS_BAND/S3/S4/S5's near-tie tie-break
# (retired 2026-08-25 -- run13_rl_grok_pipeline_analysis.md A.16). Measured
# directly as the cross-draw sd of the ARTICLE-level margin itself (winner
# R_w minus runner-up R_w, both fixed by the mean across draws), pooled
# across all 40 replicated corpus articles (production + 2 replicates each,
# temp=0.7): mean=0.0540 (n=40 articles). This is the single-draw (N=1)
# noise floor; for an article whose R_w is averaged over N draws, the
# confidence threshold shrinks by sqrt(N) -- same convention as A.7/A.11's
# defensible-share analysis (an N-draw average is less noisy than one draw).
ARTICLE_MARGIN_NOISE_SD: float = 0.054

# Below this, an arm's mean cp/ra/gsp (see _compute_gate_diagnostics) is
# reported via low_signal_flag -- informational only, never affects oracle_arm.
DIAG_LOW_SIGNAL_THRESHOLD: float = 0.85

# ---------------------------------------------------------------------------
# Manual overrides
#
# Key: article variant name  →  Value: confirmed oracle arm
#
# These take absolute precedence over the mean-R_w computation (A.16,
# 2026-08-25 -- the near-tie tie-break these were originally validated
# against, EPS_BAND/S3/S4/S5, has since been retired; see this module's
# docstring). Two categories, both still legitimate since they encode
# information R_w cannot see at all:
#   · Original 2026-06-05 cases: manual review (needs_review=True or the R_w
#     winner overridden after inspection), and near-tie cases where the
#     embedding-based S1 marginal-novelty knee (not implemented in this
#     module) was decisive.
#   · 2026-08-20/25 N=3-replication majority-vote corrections (A.15.2/
#     A.15.4): derived by majority vote of each draw's own raw R_w argmax,
#     BEFORE this module's default mechanism became mean-R_w itself -- kept
#     as independently-validated corrections, not re-derived automatically
#     by this refactor.
# ---------------------------------------------------------------------------
_MANUAL_OVERRIDES: dict[str, str] = {
    # --- manual review (needs_review=True or human inspection) ---
    "06_tools__var_minimal":               "skip",
    "11_multimodal__var_demanding":        "standard",

    # --- near-tie where S1 knee was decisive (no S4/S3/S5 actionable) ---
    # NOTE: 03_context_engineering__var_minimal removed — now covered by the
    #       external_evidence_policy=forbidden → skip hard constraint.
    "09_RAG__var_demanding":               "deep",

    # --- A.15.2/A.15.4 N=3-replication majority-vote corrections (2026-08-20,
    #     A.16.7 Phase 1). Decided by the pre-registered majority-vote-of-
    #     per-draw-arm-winners rule (production + 2 replicates), which takes
    #     precedence over compute_article_oracle's own automated near-tie S3/
    #     S4/S5 tie-break precisely because that tie-break reads only ONE
    #     arm's single-draw article text and has no cross-draw evidence.
    #     Confirmed the automated decision still disagrees with these three
    #     even after the A.16.0 ordinal-index fix (--use-averaged alone picks
    #     'deep' for both 06_tools__var_demanding and 13_agent_framework via
    #     S3/S4/S5, not the majority-vote-governed 'light') -- see
    #     run13_rl_grok_pipeline_analysis.md A.15.2/A.15.4/A.16.0.
    #     (10_memory_knowledge_access__var_demanding and
    #     02_workflows_vs_agents__var_demanding needed NO override: their
    #     2026-08-16 grade correction already made the automated decision
    #     correct at the data layer.)
    "08_react_practice__var_demanding":    "light",
    "11_multimodal__var_standard":         "skip",
    "06_tools__var_demanding":             "light",
    "Earth_Oceans_Origin":                 "deep",
    "Gravity_Entropy":                     "light",
    "13_agent_framework":                  "light",
    "Insects_Consciousness":               "deep",

    # --- 2026-08-25: N=3 promotion for 4 TEST articles that had replicate
    #     draws in noise_experiment/ but were never merged into production
    #     (assessed MODERATE risk-tier in A.15.1, lower priority than the 12
    #     CRITICAL/HIGH articles replicated in A.15.4). Decided by the SAME
    #     majority-vote-of-per-draw-raw-argmax rule as the block above (not
    #     the averaged-R_w argmax, and not compute_article_oracle's own
    #     --use-averaged tie-break output, which the A.15.4 precedent already
    #     established as untrustworthy here since S3/S4/S5 read only the
    #     single production draft's text). Votes: 29_evaluation_metrics =
    #     [light, standard, standard] -> standard (2/3, flips); HNSW =
    #     [light, light, deep] -> light (2/3, confirms, no override needed);
    #     31_CI = [light, light, skip] -> light (2/3, confirms, no override
    #     needed); State_of_LLM_Reasoning = [skip, skip, light] -> skip (2/3,
    #     confirms, and policy-forced regardless). See A.18.6 addendum.
    "29_evaluation_metrics":               "standard",
    # --- 2026-08-27: near-tie oracle review battery, distributional override
    #     (A.19). Mean-R_w argmax picks `deep` for HNSW (margin +0.0343 after
    #     this session's grading corrections, needs_review cleared), but the
    #     per-draw evidence behind that mean is not comparable to `light`'s:
    #     deep=[0.429, 0.374, 0.633] (sd=0.136) vs light=[0.433, 0.463, 0.436]
    #     (sd=0.017) -- an 8.19x sd ratio, the most extreme of the 12
    #     near-tie articles reviewed this session -- and 2 of deep's 3 draws
    #     fall entirely below light's observed range (clean maximin
    #     dominance for light; light's floor 0.433 > deep's floor 0.374).
    #     A.19 confirms this specific combination (extreme sd-ratio outlier
    #     + clean maximin dominance) does NOT replicate on the corpus's next
    #     two highest sd-ratio cases (03_context_engineering__var_standard
    #     4.80x, Bird_Eye_Extreme 2.78x, both left unchanged), so this is a
    #     narrow, dual-condition override scoped to HNSW only -- not a
    #     blanket lower-variance preference. See A.19 for the full
    #     distribution table and rule.
    "HNSW":                                "light",}

# ---------------------------------------------------------------------------
# File loaders
# ---------------------------------------------------------------------------

def _load_section_oracle(article: str, use_averaged: bool = False) -> dict:
    """Load and validate section_oracle.json (v2+) for *article*.

    ``use_averaged=True`` loads the sibling ``section_oracle_averaged.json``
    (written by merge_replicate_oracles.py) instead -- its own "version" field
    numbers the merge format, not the section_oracle.json schema, so the v2+
    check is skipped for it.
    """
    fname = "section_oracle_averaged.json" if use_averaged else "section_oracle.json"
    path = _BASES_DIR / article / fname
    if not path.exists():
        raise FileNotFoundError(f"{fname} not found for '{article}'")
    data = json.loads(path.read_text(encoding="utf-8"))
    if not use_averaged:
        v = data.get("version", 1)
        if v < 2:
            raise ValueError(
                f"section_oracle.json for '{article}' is version {v}; "
                "version 2+ required. Re-run generate_episode_oracles.py."
            )
    if not data.get("sections"):
        raise ValueError(f"{fname} for '{article}' has no sections.")
    return data


def _load_guideline_features(article: str) -> dict:
    """Load guideline_features.json for *article*."""
    path = _BASES_DIR / article / "guideline_features.json"
    return json.loads(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# R_w  (target-words-weighted mean of per-arm section rewards)
# ---------------------------------------------------------------------------

def _compute_r_w(
    oracle_sections: dict[str, dict],
    features_sections: dict[str, dict],
) -> tuple[dict[str, float], int, int, int]:
    """Return (r_w_per_arm, total_target_words, n_sections, n_with_target).

    oracle_sections  : section_oracle.json["sections"]  {sec_id: {oracle, rewards, explore?}}
    features_sections: guideline_features.json["sections"]  {sec_id: {target_words, …}}

    As of section_oracle.json version 4, each section may carry an "explore"
    sub-dict (per-arm) alongside "rewards" (per-arm, unchanged full total).
    When present, this function aggregates the two pieces DIFFERENTLY:
      - "rewards - explore" (i.e. gt_base + user_intent + cost) is averaged
        target-words-weighted, as before -- a section assigned a bigger word
        budget legitimately deserves more say over the article's overall
        content-quality/adherence/cost verdict.
      - "explore" is averaged with a SIMPLE (unweighted) mean across sections
        -- a genuinely valuable enhancement instance shouldn't count for more
        or less just because it happened to land in a long vs short section.
        See run13_rl_grok_pipeline_analysis.md Part 5 for the real-corpus case
        (13_agent_framework) that motivated this: `deep`'s enhancement
        instances were spread thin across many sections while `standard`
        concentrated instances into one heavily-weighted section, letting
        `standard` win on weight alone.
    R_w[arm] = weighted_mean(rewards[arm] - explore[arm], weights=target_words)
               + simple_mean(explore[arm])

    For version 2/3 data (no "explore" field), falls back EXACTLY to the old
    pure target-words-weighted mean of the combined "rewards" value -- zero
    behaviour change for un-migrated section_oracle.json files.
    """
    arm_acc_rest: dict[str, float] = {a: 0.0 for a in ARMS}
    arm_acc_explore: dict[str, float] = {a: 0.0 for a in ARMS}
    total_w = 0
    n_sections = 0
    n_with_target = 0
    has_explore_field = False

    for sec_id, info in oracle_sections.items():
        rewards = info["rewards"]                          # {skip, light, standard, deep}
        explore = info.get("explore")                       # v4+ only; None for v2/v3
        feat = features_sections.get(sec_id, {})
        tw_val = feat.get("target_words")
        tw = int(tw_val) if tw_val is not None else 100   # fallback weight
        if tw_val is not None:
            n_with_target += 1
        total_w += tw
        n_sections += 1

        for arm in ARMS:
            total_reward = float(rewards.get(arm, 0.0))
            if explore is not None:
                has_explore_field = True
                explore_val = float(explore.get(arm, 0.0))
                arm_acc_rest[arm] += tw * (total_reward - explore_val)
                arm_acc_explore[arm] += explore_val
            else:
                arm_acc_rest[arm] += tw * total_reward

    if total_w == 0:
        return {a: 0.0 for a in ARMS}, 0, len(oracle_sections), n_with_target

    if has_explore_field:
        r_w = {
            a: (arm_acc_rest[a] / total_w) + (arm_acc_explore[a] / n_sections)
            for a in ARMS
        }
    else:
        r_w = {a: arm_acc_rest[a] / total_w for a in ARMS}
    return r_w, total_w, n_sections, n_with_target


def _compute_gate_diagnostics(
    oracle_sections: dict[str, dict],
) -> dict[str, dict[str, float]] | None:
    """Per-arm simple mean of cp/ra/gsp across sections (unweighted -- these
    are satisficing checks, not content-value signals). Returns None when
    section_oracle.json predates the "diagnostics" field (v<5).
    """
    sums = {a: {"cp": 0.0, "ra": 0.0, "gsp": 0.0} for a in ARMS}
    n = 0
    for info in oracle_sections.values():
        diag = info.get("diagnostics")
        if diag is None:
            return None
        n += 1
        for a in ARMS:
            for k in ("cp", "ra", "gsp"):
                sums[a][k] += diag[a][k]
    if n == 0:
        return None
    return {a: {k: round(v / n, 6) for k, v in sums[a].items()} for a in ARMS}


# ---------------------------------------------------------------------------
# Oracle decision
# ---------------------------------------------------------------------------

def _decide(
    article: str,
    r_w: dict[str, float],
    n_draws: int = 1,
    external_evidence_policy: str = "allowed",
) -> tuple[str, bool, bool, list[str], list[str]]:
    """Return (oracle_arm, manual_override, needs_review, decision_path, candidate_arms).

    Pure mean-R_w argmax (A.16, 2026-08-25) -- retires the EPS_BAND/S3/S4/S5
    near-tie tie-break entirely. ``r_w`` is expected to already be the mean
    across every available draw (production + replicates, via
    section_oracle_averaged.json when it exists); ``n_draws`` says how many
    contributed, so the confidence check can shrink ARTICLE_MARGIN_NOISE_SD
    by sqrt(n_draws) -- an averaged margin is less noisy than a single draw's.

    ``candidate_arms`` is the arm set the decision actually searched over --
    ARMS unless policy=="capped" restricts it to ["skip", "light"] (A.20) --
    so the caller's runner-up/margin bookkeeping can stay scoped to the same
    set instead of always comparing against arms the policy ruled out.
    """
    # -1. Hard constraint: forbidden policy → skip, regardless of R_w.
    #     External evidence cannot be used in the final article, so the only
    #     valid production choice is the no-exploration arm.
    if external_evidence_policy == "forbidden":
        return "skip", False, False, ["policy=forbidden → skip (hard constraint)"], ARMS

    # 0.  Manual override: absolute precedence over the mean-R_w computation.
    if article in _MANUAL_OVERRIDES:
        arm = _MANUAL_OVERRIDES[article]
        return arm, True, False, [f"manual override → {arm}"], ARMS

    # Scenario C (A.20): article's own stated scope is a survey/exploitation
    # task, not a hard ban -- cap the decision to {skip, light}, never
    # standard/deep, without forcing a single fixed answer the way forbidden does.
    candidate_arms = ["skip", "light"] if external_evidence_policy == "capped" else ARMS

    ranked = sorted(candidate_arms, key=lambda a: r_w[a], reverse=True)
    best_arm = ranked[0]
    margin = r_w[best_arm] - r_w[ranked[1]]
    threshold = ARTICLE_MARGIN_NOISE_SD / (n_draws ** 0.5)
    needs_review = margin < threshold
    path = [
        f"mean R_w argmax over {n_draws} draw(s), policy={external_evidence_policy} "
        f"(candidates={candidate_arms}): {best_arm}  "
        f"margin={margin:+.4f}  1x-noise-sd threshold={threshold:.4f}  "
        f"{'BELOW threshold, low confidence' if needs_review else 'confident'}"
    ]
    return best_arm, False, needs_review, path, candidate_arms


# ---------------------------------------------------------------------------
# Build per-section output records
# ---------------------------------------------------------------------------

def _sec_id_to_title(sec_id: str) -> str:
    """Convert 'S3::section-3-choosing-your-path' → 'choosing your path'."""
    m = re.match(r"S\d+::section-\d+-(.+)$", sec_id)
    return m.group(1).replace("-", " ") if m else sec_id


def _build_section_records(
    oracle_sections: dict[str, dict],
    features_sections: dict[str, dict],
    total_target_words: int,
) -> list[dict]:
    records = []
    for i, (sec_id, info) in enumerate(oracle_sections.items()):
        rewards = info["rewards"]
        feat = features_sections.get(sec_id, {})
        tw_val = feat.get("target_words")
        tw = int(tw_val) if tw_val is not None else 100
        weight_frac = round(tw / total_target_words, 5) if total_target_words > 0 else 0.0

        sec_ranked = sorted(ARMS, key=lambda a: float(rewards.get(a, 0.0)), reverse=True)
        records.append({
            "index": i + 1,
            "sec_id": sec_id,
            "title": _sec_id_to_title(sec_id),
            "target_words": tw_val,
            "weight_words": tw,
            "weight_frac": weight_frac,
            # rewards keyed by arm name
            "rewards": {a: round(float(rewards.get(a, 0.0)), 6) for a in ARMS},
            # rewards as a list indexed 0=skip, 1=light, 2=standard, 3=deep
            # used by analyze_eval_results.py for section reward-gap analysis
            "rewards_by_preset": [
                round(float(rewards.get(a, 0.0)), 6) for a in ARMS
            ],
            "section_oracle": info.get("oracle", sec_ranked[0]),
            "section_oracle_idx": ARM_IDX.get(info.get("oracle", sec_ranked[0]), 0),
        })
    return records


# ---------------------------------------------------------------------------
# Main per-variant computation
# ---------------------------------------------------------------------------

def _variant_of(article: str) -> str:
    if "__var_minimal" in article:
        return "var_minimal"
    if "__var_demanding" in article:
        return "var_demanding"
    if "__var_standard" in article:
        return "var_standard"
    return "no_variant"  # no-variant test articles


def compute_article_oracle(article: str) -> dict:
    """Compute the full article-level oracle record for one variant.

    Sources R_w from ``section_oracle_averaged.json`` (mean across production
    + every graded replicate) whenever it exists, falling back to the
    single-draw ``section_oracle.json`` otherwise -- automatic, not a caller
    choice (A.16, 2026-08-25). This retires the earlier canonical-vs-
    ``_averaged``-sibling-file split entirely: there is no remaining reason
    to privilege the single production draw once more draws are available.

    Returns a dict ready for JSON serialisation matching the schema in
    this module's docstring.
    """
    # --- load inputs ---
    use_averaged = (_BASES_DIR / article / "section_oracle_averaged.json").exists()
    oracle_data = _load_section_oracle(article, use_averaged=use_averaged)
    oracle_sections: dict[str, dict] = oracle_data["sections"]
    n_draws = oracle_data.get("n_draws_per_arm", 1) if use_averaged else 1

    feat_data = _load_guideline_features(article)
    features_sections: dict[str, dict] = feat_data.get("sections", {})

    # --- R_w ---
    r_w, total_tw, n_sections, n_with_target = _compute_r_w(
        oracle_sections, features_sections
    )

    # --- decision ---
    oracle_arm, manual_override, needs_review, decision_path, candidate_arms = _decide(
        article, r_w, n_draws=n_draws,
        external_evidence_policy=feat_data.get("external_evidence_policy", "allowed"),
    )
    oracle_arm_idx = ARM_IDX[oracle_arm]

    # Scoped to candidate_arms so a capped article's runner-up/margin reflects
    # the actual skip-vs-light decision, not an out-of-scope standard/deep arm.
    runner_up_arm = max(
        (a for a in candidate_arms if a != oracle_arm), key=lambda a: r_w[a]
    )
    runner_up_arm_idx = ARM_IDX[runner_up_arm]
    margin = r_w[oracle_arm] - r_w[runner_up_arm]
    reward_spread = max(r_w.values()) - min(r_w.values())

    # --- section records ---
    section_records = _build_section_records(
        oracle_sections, features_sections, total_tw
    )

    gate_diagnostics = _compute_gate_diagnostics(oracle_sections)
    low_signal_flag = gate_diagnostics is not None and any(
        gate_diagnostics[a][k] < DIAG_LOW_SIGNAL_THRESHOLD
        for a in ARMS
        for k in ("cp", "ra", "gsp")
    )

    return {
        "version": 3,
        "article": article,
        "variant": _variant_of(article),
        "computed_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "computed_from": "section_oracle_averaged.json" if use_averaged else "section_oracle.json",
        "n_draws_used": n_draws,
        "oracle_arm": oracle_arm,
        "oracle_arm_idx": oracle_arm_idx,
        "runner_up_arm": runner_up_arm,
        "runner_up_arm_idx": runner_up_arm_idx,
        "margin": round(margin, 6),
        "reward_spread": round(reward_spread, 6),
        "r_w_rewards": {a: round(r_w[a], 6) for a in ARMS},
        "r_w_rewards_list": [round(r_w[a], 6) for a in ARMS],
        "decision_path": decision_path,
        "manual_override": manual_override,
        "needs_review": needs_review,
        "gate_diagnostics": gate_diagnostics,
        "low_signal_flag": low_signal_flag,
        "n_sections": n_sections,
        "n_sections_with_target": n_with_target,
        "total_target_words": total_tw,
        "sections": section_records,
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Compute article-level oracles from section_oracle.json v2 "
            "and write article_oracle.json for all 24 training variants."
        )
    )
    parser.add_argument(
        "--article",
        type=str,
        default=None,
        metavar="NAME",
        help="Process a single article-variant (default: all 24).",
    )
    parser.add_argument(
        "--articles",
        nargs="+",
        metavar="NAME",
        help="Process one or more article-variants (space-separated).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print results to stdout; do not write any files.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing article_oracle.json files (default: skip if already present).",
    )
    parser.add_argument(
        "--bases-dir",
        type=Path,
        default=None,
        help="Override the bases root (default: production rl_training_data/bases/). "
             "Must match generate_episode_oracles.py's --bases-dir for the same experiment.",
    )
    args = parser.parse_args()

    if args.bases_dir is not None:
        global _BASES_DIR
        _BASES_DIR = args.bases_dir

    if args.articles:
        targets = args.articles
    elif args.article:
        targets = [args.article]
    else:
        targets = ALL_ARTICLES

    mode = "DRY-RUN" if args.dry_run else ("FORCE" if args.force else "WRITE")
    print(
        f"compute_article_oracle.py  [{mode}]  "
        f"4-arm scheme (skip/light/standard/deep)\n"
        f"  Targets: {len(targets)} article-variant(s)\n"
    )

    results: list[dict] = []
    errors: list[tuple[str, str]] = []

    for article in targets:
        try:
            print(f"  {article} ...", end=" ", flush=True)
            data = compute_article_oracle(article)
            results.append(data)

            flag = " ★OVERRIDE" if data["manual_override"] else ""
            flag += " ⚠REVIEW" if data["needs_review"] else ""
            flag += " ⚑LOWSIG" if data["low_signal_flag"] else ""
            r_w_str = "  ".join(
                f"{a}={data['r_w_rewards'][a]:.3f}" for a in ARMS
            )
            print(
                f"oracle={data['oracle_arm']:<8}  "
                f"margin={data['margin']:+.4f}  "
                f"R_w=[{r_w_str}]{flag}"
            )

            if not args.dry_run:
                out_path = _BASES_DIR / article / "article_oracle.json"
                if out_path.exists() and not args.force:
                    print(f"  SKIP (already exists; use --force to overwrite): {out_path.name}")
                else:
                    out_path.write_text(
                        json.dumps(data, indent=2), encoding="utf-8"
                    )

        except Exception as exc:
            print(f"  ERROR: {exc}")
            errors.append((article, str(exc)))

    # --- summary table ---
    if results:
        col_w = max(len(d["article"]) for d in results) + 2
        print()
        print(
            f"  {'Article':<{col_w}}  {'Oracle':>8}  "
            f"{'Margin':>8}  Decision"
        )
        print("  " + "-" * (col_w + 60))
        for d in results:
            flags = " ★" if d["manual_override"] else "  "
            flags += "⚠" if d["needs_review"] else " "
            flags += "⚑" if d["low_signal_flag"] else " "
            path0 = d["decision_path"][0][:60] if d["decision_path"] else ""
            print(
                f"  {d['article']:<{col_w}}  "
                f"{d['oracle_arm']:<8}  "
                f"{d['margin']:>+8.4f}  "
                f"{path0}{flags}"
            )

    if not args.dry_run and results:
        print(
            f"\n  Wrote {len(results)} article_oracle.json file(s) "
            f"under rl_training_data/bases/{'  (--force active)' if args.force else ''}"
        )

    if errors:
        print(f"\n  {len(errors)} ERROR(s):")
        for art, msg in errors:
            print(f"    {art}: {msg}")
        sys.exit(1)


if __name__ == "__main__":
    main()
